# firstNumber = int(input("введите первое число"))
# secondNumber = int(input("введите воторое число"))
# simbol = input('Выберите + - * /')
# if simbol == '+':
#     print(firstNumber + secondNumber)
# elif simbol == '-':
#     print(firstNumber - secondNumber)
# elif simbol == '*':
#     print(firstNumber * secondNumber)
# elif simbol == '/':
#     try:
#         print(firstNumber / secondNumber)
#     except ZeroDivisionError:
#         print("на ноль делить нельзя")
# elif simbol == '**':
#     ken = firstNumber ** secondNumber
#     print(f"{firstNumber} ** {secondNumber}")
# elif simbol == '/':
#     ken1 = firstNumber // secondNumber
#     print(f"{firstNumber} // {secondNumber}")            
# else:
#     print("Ошибка ыыыы")


 
