#цикл
#while - пока (условия зависимый цикл)
#for - пока (не условия зависимый цикл)
# i = 1
# while i <= 5:
#     print("i, hello world")
#     i = i + 1

# #срезы [start:end:step]
# for num in  range(1, 5):
#     print(num,"Hello")   

# numbers = [1, 34, 78, 345, 111, 8, 5, 34, 9, 3, 139, 56, 2, 67, 90]
# x = []
# for number in numbers:
#     if number % 2 == 0:
#         x.append(number)
#     if number == 139:
#         break #остановить

# print(x)
 
# banana = ['apple', 'grape', 'peach', 'banan', 'orange']
# like = ['apple', 'banan']
# for i in banana:
#     if i in like:
#         print(i, "моя детка") 
# else:
#     print(i, "не любимый")