#функции
# def Hello(name, age):
#     return f'hello {name}, братик тебе можно меня ебать с {age} лет'
# print(Hello('rus', '16'))

# def calc(a,b,simbol):
#     if simbol == '+':
#         return a+b
#     elif simbol == '-':
#             return a-b

# print(calc(2,5,'-'))             

# def solution(string):
#    return string[::-1],
# # print(solution('Hello'))   

# def abbrev_name(name, Lastname):
#     return f"{name[0]}.{Lastname[0].upper()}"
# print(abbrev_name('Zhanybekov', 'Rasul'))
    

# def twice_as_old(dad_y_old, son_y_old):
#     years_ago = 0

#     while dad_y_old != 2 * son_y_old:
#         dad_y_old -= 1
#         son_y_old -= 1
#         years_ago += 1

#     return years_ago

# current_age_father = 33
# current_age_son = 16
# result = twice_as_old(current_age_father, current_age_son)
# print(result) 
arr = [1,2,3,4,5]
def grow(arr):
    for i in arr:
        i * 1
print(grow)        