#3
# user_input = input('Введите текст: ')
# count = 0
# user_input = user_input.lower()
# for char in user_input:
#     if char == 'о':
#         count += 1
# print(f'Количество букв "о" в тексте: {count}')

#4
# sum_even = 0
# length = 0
# number = int(input("Введите целое число (0 для завершения): "))
# while number != 0:
#     if number % 2 == 0:
#         sum_even += number
#     length += 1

#     number = int(input("Введите следующее целое число (0 для завершения): "))
# print(f"Длина последовательности: {length}")
# print(f"Сумма четных чисел: {sum_even}")

